### ISSUE TITLE
Ctrl + H to share isn't working after opening the three dots menu and closing it

### ISSUE THREAD

**Issue by MarcAnt01** [ikarago/Notepad#25]

**Comment by prayaas-a** [comment]
This looks like it's a UWP bug based on [this](https://stackoverflow.com/questions/53735503/keyboard-accelerator-stops-working-in-uwp-app) SO question.
Apparently (according to replies by MSFT people) this bug has been fixed as of late 2018 Insider builds (which means it likely shipped with 1903) but it's unfortunately an SDK level bug that hasn't been hotfixed for older versions of the OS yet.

**Comment by ikarago** [comment]
Like @prayaas-a said, this seems to be an UWP bug, so I won't fix this as this can only be done by Microsoft fixing this in the CommandBar itself (that is, without me having to spend a lot of time on very hacky fixes, which I rather spend fixing more major bugs in the project).

I will update the SDK once Microsoft releases that for the next big release this year, so by then it should hopefully be fixed for all. ;)

**Comment by prayaas-a** [comment]
[WinUI 3.0](https://github.com/Microsoft/microsoft-ui-xaml) can't come soon enough haha. That'll decouple the UI layer from the Windows SDK entirely, so you'll be able to target 1703 (for example) while still using the controls and bugfixes released in 2019/2020 SDKs via a NuGet package. Once WinUI 3.0 comes out, it might be a good idea to move this project to it.

For now, perhaps we could move to WinUI 2.1 (aka Microsoft.UI.Xaml via NuGet for the UI rather than the SDK's Windows.UI.Xaml). It's the latter currently iirc. It might fix this issue. What do you think @ikarago ?
