### ISSUE TITLE
Useless and ugly point hover preview in exit confirmation dialog

### ISSUE THREAD

**Issue by MarcAnt01** [ikarago/Notepad#26]
![image](https://user-images.githubusercontent.com/43090263/58021834-5f49b200-7b0c-11e9-910e-1e5cb37eb34a.png)

**Comment by prayaas-a** [comment]
From what I understand, @ikarago has enabled "keyboard accelerators" (fancy MS speak for shortcut), so you can press Y or N on the keyboard to select the corresponding action. Since Windows 10 1803, the SDK displays a tooltip with the accelerator by default unless overridden. You're right, it does look ugly and I can think of a few different changes:

- Replace the tooltip. I personally see no point in having a tooltip at all for a simple "Yes" or "No" button if it just repeats the label unless the tooltip clarifies the action such as "Discards the current document" for when you hover on "Yes". This may raise a bigger question about wording these options better for the sake of UX clarity. Microsoft discourages Yes/No/Cancel options in favor of descriptive ones like Discard/Save. I'll make a separate issue for that one.

- Make the keyboard accelerator actually appear on the right side of the button in lighter text for better discoverability. Here's an example:
![Keyboard Accelerator Visibility Example](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml/images/keyboard-accelerators.png)
It would then make more sense to remove the tooltip.

**Comment by ikarago** [comment]
Is this more to your liking? :)

![image](https://user-images.githubusercontent.com/19528662/63290360-98d3ba00-c2c1-11e9-94e2-1c5906c257ef.png)

**Comment by MarcAnt01** [comment]
I don't like Y/N in general, but in this way it looks better👍

**Comment by prayaas-a** [comment]
Great for discoverability! And what happens when you hover? Did you get to change the tool tip?

**Comment by ikarago** [comment]
I have been able to hide the tooltips for now, as I'm not sure if it would be better UX if the ToolTip explains the option or just not show up at all (as all needed info is already in sight)

**Comment by prayaas-a** [comment]
Yeah the tool tip would be redundant I think

**Comment by ikarago** [comment]
I've redone the wording of the dialog. What do you think @MarcAnt01?

![image](https://user-images.githubusercontent.com/19528662/63291414-c1f54a00-c2c3-11e9-80ee-61d76a23e75b.png)

**Comment by MarcAnt01** [comment]
I like it, good work @ikarago
